# Generated by Django 3.1.12 on 2022-08-23 00:24

import deepcom.custom_models.Events
import deepcom.custom_models.processing_parameters
import deepcom.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingParametersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preprocess', djongo.models.fields.EmbeddedField(default={'top_hat': {'kernelHeight': 9, 'kernelWidth': 9}}, model_container=deepcom.custom_models.processing_parameters.PreprocessParameters)),
                ('process', djongo.models.fields.EmbeddedField(default={'threshold': {'thresh': 20}}, model_container=deepcom.custom_models.processing_parameters.ProcessParameters)),
                ('events', djongo.models.fields.EmbeddedField(default={'minArea': 200}, model_container=deepcom.custom_models.processing_parameters.EventsParameters)),
                ('video_linked', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_path', models.CharField(max_length=255)),
                ('status', models.CharField(default='unprocessed', max_length=255)),
                ('by_second', djongo.models.fields.ArrayField(model_container=deepcom.models.Second)),
                ('seconds_with_events', djongo.models.fields.ArrayField(model_container=deepcom.models.EventInstant)),
                ('events', djongo.models.fields.ArrayField(model_container=deepcom.custom_models.Events.EventModel)),
                ('spent_time', models.FloatField(null=True)),
            ],
        ),
    ]
