# Generated by Django 3.1.12 on 2022-06-30 20:20

import deepcom.custom_models.processing_parameters
import deepcom.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingParametersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preprocess', djongo.models.fields.EmbeddedField(model_container=deepcom.custom_models.processing_parameters.PreprocessParameters)),
                ('video_linked', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_path', models.CharField(max_length=255)),
                ('status', models.CharField(default='UNPROCESSED', max_length=255)),
                ('frames', djongo.models.fields.ArrayField(model_container=deepcom.models.Frame, model_form_class=deepcom.models.FrameForm)),
            ],
        ),
    ]
