# Generated by Django 3.1.12 on 2022-06-30 20:23

import deepcom.custom_models.processing_parameters
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deepcom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingparametersmodel',
            name='preprocess',
            field=djongo.models.fields.EmbeddedField(default={'top_hat': {'kernelHeight': 9, 'kernelWidth': 9}}, model_container=deepcom.custom_models.processing_parameters.PreprocessParameters),
        ),
    ]
