# Generated by Django 4.0.5 on 2022-06-11 01:43

import deepcom.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deepcom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedVideo',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('video_path', models.CharField(max_length=255)),
                ('data', djongo.models.fields.ArrayField(model_container=deepcom.models.ParticleData, model_form_class=deepcom.models.ParticleDataForm)),
            ],
        ),
        migrations.DeleteModel(
            name='ParticleData',
        ),
    ]
