name: CD
run-name: ${{ github.actor }} is running CD flow
on:
  push:
    branches:
      - 'main'

jobs:
docker-cd:
  runs-on: ubuntu-latest
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Checkout code
      uses: actions/checkout@v2
          
    - name: Get short SHA
      run: |
        echo "Getting short SHA..."
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "SHA short is $sha_short"
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.0.2
      with:
        push: true
        tags: miguelmartinr/deepview:latest, miguelmartinr/deepview:${{ env.sha_short }}